services:
  federated-data-management-portal:
    build: .
    volumes:
      - ./data:/data:ro
    environment:
      - SCHEMA_FILE_PATH=/data/schema.json
      - DASHBOARD_DATA_FILE_PATH=/data/dashboard.json
    ports:
      - 8050:8050
